// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto3DS.Controllers;

#nullable disable

namespace Projeto3DS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240514175239_PopCategoria")]
    partial class PopCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto3DS.Models.Categoria", b =>
                {
                    b.Property<int>("categoria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("categoria_nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("categoria_id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Projeto3DS.Models.Tenis", b =>
                {
                    b.Property<int>("tenis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("categoria_id")
                        .HasColumnType("int");

                    b.Property<int?>("categoria_id1")
                        .HasColumnType("int");

                    b.Property<string>("desc_curta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("desc_detalhe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("em_estoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("img_miniatura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("img_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("tenis_id");

                    b.HasIndex("categoria_id1");

                    b.ToTable("Tenis");
                });

            modelBuilder.Entity("Projeto3DS.Models.Tenis", b =>
                {
                    b.HasOne("Projeto3DS.Models.Categoria", null)
                        .WithMany("Tenis")
                        .HasForeignKey("categoria_id1");
                });

            modelBuilder.Entity("Projeto3DS.Models.Categoria", b =>
                {
                    b.Navigation("Tenis");
                });
#pragma warning restore 612, 618
        }
    }
}
